### ISSUE TITLE
VSS not possible with ROBOCOPY-BACKUP

### ISSUE THREAD

**Issue by individual-it** [International-Nepal-Fellowship/Windows-Tools#42]
When using Volume Shadow copy with ROBOCOPY-BACKUP the source is not found and the software runs forever. Here the log:

```
ROBOCOPY-BACKUP 1.0.ALPHA.3
   
     
Robocopy mirror from \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy13\Shares\Community-Mgmt to \\banke-dc-01\remoteofficebackup\simpani-dc-01\Community-Mgmt (\\banke-dc-01\remoteofficebackup\)

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows                              
-------------------------------------------------------------------------------

  Started : Thu Apr 23 18:06:06 2015

2015/04/23 18:06:06 ERROR 123 (0x0000007B) Getting File System Type of Source \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy13\Shares\Community-Mgmt\
The filename, directory name, or volume label syntax is incorrect.

   Source - \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy13\Shares\Community-Mgmt\
     Dest : \\banke-dc-01\remoteofficebackup\simpani-dc-01\Community-Mgmt\

    Files : *.*
	    
  Options : *.* /S /E /COPY:DAT /PURGE /MIR /Z /XJ /R:1000000 /W:30 

------------------------------------------------------------------------------

2015/04/23 18:06:08 ERROR 53 (0x00000035) Accessing Source Directory \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy13\Shares\Community-Mgmt\
The network path was not found.
Waiting 30 seconds... Retrying...
2015/04/23 18:06:41 ERROR 53 (0x00000035) Accessing Source Directory \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy13\Shares\Community-Mgmt\
The network path was not found.
Waiting 30 seconds... Retrying...
2015/04/23 18:07:13 ERROR 53 (0x00000035) Accessing Source Directory \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy13\Shares\Community-Mgmt\
The network path was not found.
```

**Comment by phil-davis** [comment]
I noticed this again today and researched it. robocopy seems to not be capable of using the special Volume Shadow disk name format.
The way around it seems to be to make a soft link to the Volume Shadow disk and use the soft link with robocopy to read the source files. e.g.
```mklink /D C:\zzz \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy25\```
I will think about how to best implement this - the ordinary robocopy-backup running without volume shadow is sometimes getting stuck forever on reading an open file, so the volume shadow would be great to have.

**Comment by phil-davis** [comment]
The other alternative seems to be to using the vshadow.exe utility
https://msdn.microsoft.com/en-us/library/windows/desktop/bb530725%28v=vs.85%29.aspx
That can make a volume shadow be exposed as a drive letter, or in a folder.
But vshadow.exe does not seem to be built-in to Windows, so that would be another magic utility that would have to be added to systems.

**Comment by phil-davis** [comment]
Fixed by https://github.com/International-Nepal-Fellowship/Windows-Tools/pull/52
