### ISSUE TITLE
-backupsToKeep 1 doing Copy rather than Mirror

### ISSUE THREAD

**Issue by geo-it** [International-Nepal-Fellowship/Windows-Tools#56]
When using "-backupsToKeep 1" ntfs-hardlink-backup does a full copy where it should do a mirror. Maybe this is as intended but the help file specifically mentions a mirror.

It looks like the "get me the last backup if any" code only works for previous backups with the date and time at the end. The "-backupsToKeep 1" option leaves the date-time off the directory name so there is no last backup folder match and the script uses "ln.exe --copy" into an existing backup directory.

**Comment by individual-it** [comment]
Sorry for the late reply, I wasn't on this project for a while
I think what you describe is intended
What do you think @phil-davis ?

**Comment by geo-it** [comment]
It's up to you if this is as intended. The main difference between a mirror and a copy is the handling of deleted files. In the case where backupsToKeep is greater than 1 the deleted files are retained in earlier dated backup folders and removed in ones dated after the file was deleted. In the case where backupsToKeep is 1, and the current code doing a copy rather than a delete, the deleted files are retained in the one backup folder.

So, for example, if you have a source folder that is cleared each day except for a new file with an incrementing date in the file name the current backup code will keep one backup folder and keep copying the new files into the backup folder and never remove the earlier files. If that one file is large you'll quickly eat up all your backup space. Even if not you'll eventually run out of space.

**Comment by phil-davis** [comment]
I think it is better that it does a mirror. If people want to keep old (deleted) files then they should be setting backupstokeep>1 and thus getting a suitable backup history.
PR #59

**Comment by phil-davis** [comment]
Note: There is danger in any backup scheme that keeps only a single copy (mirror or whatever you may call it):
a) If a file is deleted in the source, it is gone from the backup at the next backup run.
b) During the running of the backup, the backup destination is inconsistent with-respect-to both the previous backup and the current source. An interrupted backup leaves the backup destination in a potentially corrupt state (specially if the files make up a database or... where the state of multiple files needs to be consistent). So in this kind of case there might be no known-good backup in existence.

So backupstokeep=1 should only be used after understanding the danger.

(just writing this here for the benefit of any future readers)

**Comment by geo-it** [comment]
This is great. Thank you.

With this change I can cover all my use cases without also needing to deploy your robocopy-backup script. Although that is also a useful script.

Thank you again.
